host = "0.0.0.0"
port = 3000
log_level = "debug"

[netio]
workers = 2
reuse_port = true
uring_entries = 1024
socket_recv_buffer_size = 33554432
socket_send_buffer_size = 33554432

[netio.buffer_pool]
max_buffers = 16384
datagram_size = 1350