host = "0.0.0.0"
port = 3000
log_level = "info"

[telemetry]
otlp_endpoint = "http://localhost:4317"
service_name = "quicd"
enable_metrics = true
enable_tracing = false
export_interval_secs = 60

[netio]
workers = 2
reuse_port = true
uring_entries = 1024
socket_recv_buffer_size = 33554432
socket_send_buffer_size = 33554432

[netio.buffer_pool]
max_buffers = 16384
datagram_size = 1350