//! QUIC protocol layer using Cloudflare Quiche.
//!
//! **Architecture**: Event-driven QUIC processing integrated with io_uring network layer.
//!
//! # Design Principles
//!
//! - **Per-Worker State**: Each worker thread has its own connection manager
//! - **Event-Driven**: QUIC processing happens on same thread as network I/O
//! - **Zero-Copy**: Reuses buffer pool from network layer
//! - **No Sharing**: Connection state never crosses thread boundaries
//! - **Pre-allocation**: Connection and stream data structures pre-allocated
//!
//! # Integration with Network Layer
//!
//! ```text
//! io_uring receives packet
//!   ↓
//! QuicManager::process_ingress()
//!   ↓
//! Route to Connection (by DCID)
//!   ↓
//! quiche::Connection::recv()
//!   ↓
//! Process streams (application data)
//!   ↓
//! quiche::Connection::send()
//!   ↓
//! Submit egress via io_uring
//! ```
//!
//! # Per-Worker Components
//!
//! - `QuicManager`: Manages all connections for this worker
//! - `QuicConnection`: Wrapper around quiche::Connection
//! - Connection map: DCID → QuicConnection
//! - Timer wheel: For connection timeouts and retransmissions
//!
//! # Quiche Integration
//!
//! We use Cloudflare's Quiche library which provides:
//! - Full QUIC v1 (RFC 9000) implementation
//! - TLS 1.3 handshake handling
//! - Congestion control (BBR, Cubic, etc.)
//! - Stream multiplexing
//! - Loss detection and recovery
//! - Flow control
//!
//! Our role is to:
//! - Feed received packets to Quiche
//! - Send packets generated by Quiche
//! - Manage connection lifecycle
//! - Handle application-layer streams (future)

pub mod config;
pub mod connection;
pub mod crypto;
pub mod ebpf_routing;
pub mod manager;

pub use config::QuicConfig;
pub use ebpf_routing as routing;
pub use manager::QuicManager;
