use std::net::SocketAddr;
use std::time::Instant;

use bytes::Bytes;

use crate::error::ConnectionError;
use crate::handle::{ConnectionStats, RecvStream, SendStream, StreamId};

/// Events raised by the worker runtime toward an application task.
///
/// These events are delivered in order to the application via `AppEventStream`.
/// All events are generated by the worker thread, never blocked; the app processes them
/// asynchronously.
#[derive(Debug)]
pub enum AppEvent {
    /// Transport handshake completed; application can start protocol work.
    ///
    /// This is the first event sent to the application after a QUIC connection
    /// completes its TLS handshake. The app should now be prepared to receive
    /// or send streams and datagrams.
    HandshakeCompleted {
        /// ALPN negotiated during handshake
        alpn: String,
        /// Local socket address for this connection
        local_addr: SocketAddr,
        /// Peer socket address
        peer_addr: SocketAddr,
        /// Time the handshake completed
        negotiated_at: Instant,
    },

    /// Peer opened a new bidirectional or unidirectional stream.
    ///
    /// This event is generated when a stream is initiated by the peer.
    /// - For bidirectional streams: `send_stream` is `Some`; app can read and write
    /// - For unidirectional streams: `send_stream` is `None`; app can only read
    ///
    /// The app should spawn a task or enter a handler to process this stream.
    NewStream {
        /// Unique identifier for this stream
        stream_id: StreamId,
        /// True if bidirectional, false if unidirectional from peer
        bidirectional: bool,
        /// Receiver endpoint for stream data (zero-copy)
        recv_stream: RecvStream,
        /// Sender endpoint (only present for bidirectional)
        send_stream: Option<SendStream>,
    },

    /// Peer has finished sending data on a stream (FIN received).
    ///
    /// This is informational; `RecvStream::read()` will return `Ok(None)` afterwards.
    StreamFinished { stream_id: StreamId },

    /// Stream was explicitly closed or reset by the peer.
    ///
    /// This signals an abnormal stream termination with an error code.
    StreamClosed {
        stream_id: StreamId,
        /// True if the application initiated the close
        app_initiated: bool,
        /// Application-defined error code
        error_code: u64,
    },

    /// Unreliable datagram payload received from the peer.
    ///
    /// Only sent if datagrams are negotiated in the transport controls.
    /// Each datagram is independent; loss does not affect other datagrams or streams.
    Datagram { payload: Bytes },

    /// Flow-control parameters updated (e.g., max streams limit changed).
    ///
    /// The app may want to check `ConnectionHandle::stats()` to learn new limits.
    ConnectionCapacityChanged,

    /// Transport-level signal delivered to the application.
    ///
    /// These are informational events about the underlying QUIC transport.
    TransportEvent(TransportEvent),

    /// Connection is closing; application should start tearing down state.
    ///
    /// After this event, no more data can be sent or received. The application
    /// task will end shortly after. Use this event to clean up resources gracefully.
    ConnectionClosing {
        /// QUIC error code from the peer (or generated locally)
        error_code: u64,
        /// Optional reason string from the peer
        reason: Option<Bytes>,
    },

    /// Response to `ConnectionHandle::open_bi()` command.
    ///
    /// The request_id correlates with the original request.
    /// On success, the app receives both send and recv endpoints.
    StreamOpened {
        request_id: u64,
        result: Result<(SendStream, RecvStream), ConnectionError>,
    },

    /// Response to `ConnectionHandle::open_uni()` command.
    ///
    /// On success, the app receives only a send endpoint (can't receive on uni streams
    /// initiated by server).
    UniStreamOpened {
        request_id: u64,
        result: Result<SendStream, ConnectionError>,
    },

    /// Response to `ConnectionHandle::send_datagram()` command.
    ///
    /// On success, indicates the number of bytes sent.
    DatagramSent {
        request_id: u64,
        result: Result<usize, ConnectionError>,
    },

    /// Response to `ConnectionHandle::reset_stream()` command.
    StreamReset {
        request_id: u64,
        result: Result<(), ConnectionError>,
    },

    /// Response to `ConnectionHandle::stats()` command.
    ///
    /// Returns a snapshot of connection-level statistics.
    StatsReceived {
        request_id: u64,
        result: Result<ConnectionStats, ConnectionError>,
    },
}

/// Transport-level events from the QUIC layer.
///
/// These events are informational and do not require action from the application,
/// but the app may want to adjust behavior based on them (e.g., react to congestion).
#[derive(Debug)]
pub enum TransportEvent {
    /// Peer has migrated to a new network path.
    ///
    /// Indicates that packets are now being received from a different address.
    /// The connection remains valid; the QUIC protocol handles this transparently.
    PathMigrated { new_peer_addr: SocketAddr },

    /// Effective Maximum Transmission Unit (MTU) changed for the connection.
    ///
    /// The underlying network path has changed, affecting packet size limits.
    /// Applications sending datagrams may want to adjust payload sizes.
    MtuUpdated { mtu: usize },

    /// Congestion control state changed.
    ///
    /// Can indicate transitions between normal, slow-start, or recovery states.
    /// Applications may use this to adjust sending behavior (e.g., adaptive bitrate).
    CongestionStateChanged { state: String, bytes_in_flight: u64 },

    /// Catch-all for transport events not covered by dedicated variants yet.
    ///
    /// Future QUIC events will be added as dedicated variants.
    Other { kind: String },
}
